spring.application.name=Backend

# Endereço do banco de dados
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
# Usuário do banco de dados
spring.datasource.username=RM0000
# Senha do banco de dados
spring.datasource.password=SENHA
# Mostrar as instruções SQL
# executadas no banco de dados
spring.jpa.show-sql=true
